version: '3'

networks:
    bibbox-default-network:
      external: true

services:

  local-openspecimen-db:
    image: mysql:8.0.26
    container_name: local-openspecimen-db
    restart: unless-stopped
    networks:
      - bibbox-default-network
    environment:
      - MYSQL_ROOT_PASSWORD=openspecimen
      - MYSQL_DATABASE=openspecimen
      - MYSQL_USER=openspecimen
      - MYSQL_PASSWORD=openspecimen
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./configs/openspecimen.cnf:/etc/mysql/conf.d/openspecimen.cnf:ro #read only 
    cap_add:
      - SYS_NICE 
      
  local-openspecimen-web:
    image: bibbox/openspecimen:v10.1.RC1
    container_name: local-openspecimen-web
    user: tomcat
    restart: unless-stopped
    networks:
      - bibbox-default-network
    links:
      - local-openspecimen-db:openspecimen-db
    environment:
      - CATALINA_OPTS="-Xmx2048m"
      - DATABASE_HOST=openspecimen-db
      - DATABASE_PORT=3306
      - MYSQL_ROOT_PASSWORD=openspecimen
      - MYSQL_DATABASE=openspecimen
      - MYSQL_USER=openspecimen
      - MYSQL_PASSWORD=openspecimen
    depends_on:
      - local-openspecimen-db
    volumes:
      - ./data/os-data:/var/lib/openspecimen/data
      - ./data/os-plugins:/var/lib/openspecimen/plugins
      - ./configs/openspecimen/ROOT:/var/lib/tomcat9/webapps/ROOT
    ports:
      - "9000:8080"
